import { GoogleGenAI, Type } from '@google/genai';
import { Summary } from '../../src/types';
import { withRetry } from '../utils/retry';
import { Config } from '../lib/config';

export class LLMService {
  static async summarize(transcript: string): Promise<Summary> {
    const apiKey = Config.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY is not configured');
    }

    return withRetry(async () => {
      console.log('[LLMService][SUMMARIZATION_ATTEMPT]');
      const ai = new GoogleGenAI({
        apiKey,
        httpOptions: {
          headers: {
            'User-Agent': 'aistudio-build',
          }
        }
      });

      const prompt = `
        Analyze the following transcript and provide a structured summary in JSON format.
        
        Transcript:
        "${transcript}"
      `;

      const response = await ai.models.generateContent({
        model: 'gemini-3.6-flash',
        contents: prompt,
        config: {
          systemInstruction: 'You are an expert assistant specialized in note-taking and summarization. Provide a structured summary with an executive summary (3-5 sentences), key highlights (3-7 points), and action items (next steps or decisions). Return ONLY a JSON object matching the required schema.',
          responseMimeType: 'application/json',
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              executive_summary: {
                type: Type.STRING,
                description: "A concise 3–5 sentence overview of the recording."
              },
              key_highlights: {
                type: Type.ARRAY,
                items: { type: Type.STRING },
                description: "3–7 important points from the transcript."
              },
              action_items: {
                type: Type.ARRAY,
                items: { type: Type.STRING },
                description: "Important tasks, decisions, follow-ups, or next steps. Return empty array if none."
              }
            },
            required: ['executive_summary', 'key_highlights', 'action_items']
          }
        }
      });

      const text = response.text;
      if (!text) {
        throw new Error('No summary content was generated by Gemini');
      }
      
      // Clean markdown formatting if present
      const cleanedText = text
        .replace(/^```json\s*/i, '')
        .replace(/^```\s*/, '')
        .replace(/\s*```$/, '')
        .trim();

      const parsed = JSON.parse(cleanedText) as Partial<Summary>;

      const summary: Summary = {
        executive_summary: parsed.executive_summary || 'No executive summary provided.',
        key_highlights: Array.isArray(parsed.key_highlights) ? parsed.key_highlights : [],
        action_items: Array.isArray(parsed.action_items) ? parsed.action_items : []
      };

      return summary;
    }, {
      onRetry: (error, attempt) => {
        console.warn(`[LLMService][RETRY] Attempt ${attempt} failed: ${error.message}`);
      }
    });
  }
}

